# Server
server.port=8080




# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialect is automatically detected in Hibernate 6+
spring.jpa.properties.hibernate.format_sql=true

# Initialize data.sql after JPA
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# JWT
jwt.secret=pmsSecretKey2024SuperLongKeyForHMacSHA256SigningAlgorithm!@#
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:4200

# Logging
logging.level.com.pms=DEBUG
logging.level.org.springframework.security=DEBUG